### PR TITLE
file: support for spaces in baseUrl

### LINKED ISSUE #10: Relative links with spaces in the baseUrl will fail
Related to https://github.com/tcort/markdown-link-check/issues/15 

I can continue to reproduce the problem in #15 with the exact same steps. If you add the line

```
[A](./A.md)
```

to your file [A.md](https://github.com/tcort/link-check/blob/master/test/fixtures/s%20p%20a%20c%20e/A.md) you should be able to see what I mean.

```sh
$ cd link-check
$ markdown-link-check test/fixtures/s\ p\ a\ c\ e/A.md
[✖] ./A.md

ERROR: dead links found!
```

Here's the relevant code in file.js:

https://github.com/tcort/link-check/blob/7af6427ee10f8684b18a96ff4e35232eeba6cea8/lib/proto/file.js#L10-L15

In your previous patch to this issue you added a `decodeURIComponent` on line 11. However, if 
the `opts.baseUrl` has spaces in it, `then url.parse` will convert them to `%20` on line 13. And then the call to `fs.access` will fail to find the file. 

In your current unit test for this, the spaces don't occurr in the baseUrl, they occurr in the filepath. These are never escaped and therefore your unit test passes.

I modified the test to get it to fail by changing filePath to 'A.md' and baseUrl to include the full path. This more closely simulates how markdown-link-check invokes link-check from the command line.

I resolved the issue by using decodeURI on line 13. 

I have a patch with all of this in it, including the change to `A.md`. I plan to submit a pull request right after this.

### PR DESCRIPTION
**Pull request by michaelgwelch**
Fixes #10.

### CODE REVIEW

File: lib/proto/file.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ module.exports = {
     check: function (link, opts, callback) {
         let filepath = decodeURIComponent(url.parse(link, false, true).path || '');
         if (!path.isAbsolute(filepath)) {
-            const basepath = url.parse(opts.baseUrl, false, true).path || processModule.cwd();
+            const basepath = decodeURI(url.parse(opts.baseUrl, false, true).path || processModule.cwd());
```
Comment (michaelgwelch) [inline lib/proto/file.js]: Probably can scope the decodeURI to the parse call instead of including the call to `cwd`

File: test/link-check.test.js [hunk 2]
```diff
@@ -178,7 +178,7 @@ describe('link-check', function () {
     });
 
     it('should handle file path containing spaces', function(done) {
-        linkCheck('fixtures/s p a c e/A.md', { baseUrl: 'file://' + __dirname }, function(err, result) {
+        linkCheck('A.md', { baseUrl: 'file://' + __dirname + '/fixtures/s p a c e'}, function(err, result) {
```
Comment (michaelgwelch) [inline test/link-check.test.js]: I guess I should have left this test in place (since it tests the file path) and add a new test, that tests the baseUrl.

I can add that to this pull request so that you have coverage for both.
